# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vif < Formula
  desc "AI video frame interpolation TUI"
  homepage "https://github.com/kesonglab/video-interpolate"
  version "0.3.1-rc1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kesonglab/video-interpolate/releases/download/v0.3.1-rc1/vif_0.3.1-rc1_darwin_amd64.tar.gz"
      sha256 "3ae85bd30fa2296929742472ff062c42e1b39fc0073b55e974ba41843c23d063"

      define_method(:install) do
        bin.install "vif"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kesonglab/video-interpolate/releases/download/v0.3.1-rc1/vif_0.3.1-rc1_darwin_arm64.tar.gz"
      sha256 "1ae018f999e51b867be2cd6c3f8b00d6bd266d56476114569d6fbc0eaeefa27c"

      define_method(:install) do
        bin.install "vif"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kesonglab/video-interpolate/releases/download/v0.3.1-rc1/vif_0.3.1-rc1_linux_amd64.tar.gz"
      sha256 "b90d2c2da5fd54636a81d2762f2fe4588502d529014c8dd9cfe467fe1bdce476"
      define_method(:install) do
        bin.install "vif"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kesonglab/video-interpolate/releases/download/v0.3.1-rc1/vif_0.3.1-rc1_linux_arm64.tar.gz"
      sha256 "48b58ce58162dacf3a0ac62b204d0c354e927d1afc5e9579cad75b4f5394cbec"
      define_method(:install) do
        bin.install "vif"
      end
    end
  end

  test do
    system "#{bin}/vif", "version"
  end
end
